import type { SeedConfig } from "../types.js";

export const SEEDS: SeedConfig[] = [
  {
    domain: "arla.dk",
    sitemapUrl: "https://arla.dk/sitemap.xml",
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "dk-kogebogen.dk",
    sitemapUrl: undefined,
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "madensverden.dk",
    sitemapUrl: "https://madensverden.dk/sitemap.xml",
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "nemlig.com",
    sitemapUrl: undefined,
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "spisbedre.dk",
    sitemapUrl: "https://spisbedre.dk/sitemap.xml",
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "mummum.dk",
    sitemapUrl: "https://mummum.dk/sitemap_index.xml",
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
  {
    domain: "juliebruun.com",
    sitemapUrl: "https://juliebruun.com/sitemap_index.xml",
    requiresJs: false,
    respectRobotsTxt: true,
    maxPages: 5000,
    admissionRole: "trusted",
  },
];
