/** Language of each source's configured recipe catalogue, not its cuisine or TLD.
 * Seeded from the legacy spiders' explicit country labels and Danish defaults.
 * ScandiKitchen is English despite its legacy Danish default. Localized brand
 * routes (e.g. Danish Crown and Nutella) retain their configured Danish locale.
 * Keep canonical IDs explicit: new sources must be classified, never guessed
 * from a hostname. Registry coverage is checked in source-languages.test.ts.
 * This metadata is self-contained; runtime does not need the legacy project.
 */
export type RecipeSourceLanguage = "da" | "en";

export const RECIPE_SOURCE_IDS_BY_LANGUAGE: Record<RecipeSourceLanguage, readonly string[]> = {
  da: [
    "365discount", "airfryerkogebogen", "airfryermad", "albertestengaard", "alcayaga", "alt",
    "altmad", "amo", "amorsmadklub", "anicula", "annamaddk", "annesondergaard", "aperol", "arla",
    "aurion", "avocadoen", "babybite", "bageglad", "bagvrk", "bareencocktail", "baregomad",
    "basisvarer", "beauvais", "becel", "bedstedrinks", "bedstemorskogebog", "beetrootbakery",
    "benedictesmad", "bergholts", "blenderopskrifter", "bobedre", "bodylab", "bondemad",
    "bornemenuen", "bornholms", "camillemaja", "campari", "carrotstick", "castello", "chilisauce",
    "chokomils", "christinaskoekken", "cocktaily", "cookingclub", "coop", "copenhagendistillery_da",
    "dagenstallerken", "danishcrown", "danishthings", "dansktang", "diabetesopskrifter",
    "dittejulie", "dkkogebogen", "drdk", "drkoch", "emmaolsen", "evatrio", "familiejournal",
    "femina", "ferrerorocher", "fevertree", "foodfanatic", "foodnotes", "frahaventilmaven",
    "frederikkewaerens", "friluftslageret", "frokenkraesen_com", "frukreativ", "fuldkorn",
    "gamleopskrifter", "gastrofun", "gastrologik", "gastromad", "gastromand", "gastrotools",
    "gastry", "gigtforeningen", "glutenfrimagi", "glyngoere", "gocook", "gourministeriet",
    "grilltips", "groedgrisen", "gunris", "hannerobinson", "hashtagmor", "heidiogper", "heinz",
    "hejholger", "hellofresh", "hoerup", "homebybianca", "hurtigmums", "hverdagsgourmet",
    "hverdagskoekken", "hverdagsro", "hvidlogvin", "iform", "imerco", "ingridhornshoj",
    "italienskvinogmad", "jensensmadblog", "johanjohansen", "jonsmadklub", "juliebruun",
    "juliekarla", "kagefest", "kagerogsager", "karinabaagoe", "kenwoodworld", "ketoliv", "ketomums",
    "kikkoman", "kitchenaid", "klank", "klinksgaard", "knaehoejkarse", "kokke",
    "kokkeriermedpassion", "kornkammeret", "koudahl", "kystfisken", "letmad", "louiogbearnaisen",
    "louisesmadblog", "lundoaagaard", "lurpak", "madbanditten", "madenimitliv", "madensverden",
    "madentusiasten", "madfilosofie", "madfolket", "madforfattigroeve", "madformadelskere",
    "madhang", "madmors", "madmusen", "madogdrikke", "madoghave", "madogkaerlighed",
    "madogmonopolet", "madopskriften", "madopskriftertilairfryer", "madrejsen", "madskribent",
    "madsvin", "maduniverset", "majspassion", "mambeno", "marialottes", "mariasilje",
    "mariavestergaard", "meny", "mettesmadmagi", "meyers", "micadeli", "minmadopskrift",
    "minopskrift", "mondaybliss", "mummum", "mutti", "muttionline", "nannapretzmann", "nemlchf",
    "nemlig", "nemmadplan", "nerdytreats", "nescafe", "netto", "newyorkerbyheart", "nipunijulie",
    "nogetiovnen", "nordmad", "nutella", "oatly", "odensemarcipan", "oetker", "onekitchenblog",
    "opskrifterdk", "opskrifterforalle", "opskrifteriet", "opskriftnet", "opskriftorg",
    "opskriftslageret", "parcelhuslykke", "pigenikoekkenet", "pilenskoekken", "planetariskkogebog",
    "planteaederen", "plantepusherne", "puredansk", "rasmussmedstrup", "recipesairfryer_dk",
    "rema1000", "revivafit", "rigeligtsmor", "rosekylling", "sabinasverden", "samvirke",
    "santamariaworld", "schulstad", "semper", "sixpm", "skalvibage", "skolemaelk", "slagterlampe",
    "smaagroenneskridt", "spicytwist", "spisbedre", "spisekunst", "starbucksathome", "stegeso",
    "stinna", "sundfamiliemad", "sundmor", "sundpaabudget", "surdejmedsophie", "surdejsentusiasten",
    "sydhavnsbloggen", "thefoodclub", "tv2mad", "twinfood", "udeoghjemme", "veganermor",
    "veganernu", "vegetariskhverdag", "vforvegetarisk", "vielskermad", "vinpusheren", "violife",
    "webopskrifter",
  ],
  en: [
    "40aprons", "abakershouse", "acedarspoon", "acouplecooks", "acozykitchen", "addapinch",
    "addictedtodates", "afamilyfeast", "africanbites", "afullliving", "aggieskitchen",
    "agirldefloured", "ahintofrosemary", "aimadeitforyou", "airfryeryum", "alattefood",
    "alittlebitofspice", "alldayidreamaboutfood", "allergylicious", "allrecipes", "allshecooks",
    "alphafoodie", "altonbrown", "alwaysusebutter", "amandascookin", "amiraspantry",
    "amuseyourbouche", "amyinthekitchen", "amyshealthybaking", "anaffairfromtheheart",
    "andiemitchell", "anitalianinmykitchen", "annsentitledlife", "anoregoncottage", "apeachyplate",
    "aprettylifeinthesuburbs", "artfuldishes", "artofnaturalliving", "aseasyasapplepie",
    "asimplepalate", "askchefdennis", "aspicyperspective", "asweetspoonful", "athomewithshay",
    "averiecooks", "avocadosfrommexico", "bakedambrosia", "bakedbyrachel", "bakefromscratch",
    "bakeitwithlove", "bakeorbreak", "bakeplate", "bakeplaysmile", "bakerbynature", "bakerella",
    "bakerita", "bakesbybrownsugar", "bakingamoment", "bakingbeauty", "bakingginger",
    "bakingmischief", "barefeetinthekitchen", "barleyandsage", "bbcgoodfood", "beamingbaker",
    "bellalimento", "bellyfull", "berlyskitchen", "berrymaple", "bertolli", "bessiebakes",
    "bestrecipebox", "bettycrocker", "beyondkimchee", "biancazapatka", "biggerbolderbaking",
    "bigrecipe", "biscuitsandburlap", "biteswithbri", "blackberrybabe", "blackpeoplesrecipes",
    "blendwithspices", "bluebowlrecipes", "bobsredmill", "boulderlocavore", "bowlofdelicious",
    "breadboozebacon", "breadtopia", "brighteyedbaker", "brownedbutterblondie", "browneyedbaker",
    "budgetbytes", "buildyourbite", "bunnyswarmoven", "butterandbaggage", "butterandbliss",
    "butternutbakeryblog", "butteryourbiscuit", "cafedelites", "cakebycourtney", "cakenknife",
    "cakewhiz", "callmepmc", "canadianliving", "caramelandcashews", "caribbeangreenliving",
    "caribbeanpot", "carlsbadcravings", "casuallypeckish", "centercutcook", "cheerfulcook",
    "chefjeanpierre", "cheflindseyfarr", "cheflolaskitchen", "chefnotrequired", "chelsea_nz",
    "chelseasmessyapron", "cheneetoday", "chewoutloud", "chicagojogger", "chocolatecoveredkatie",
    "choosingchia", "ciaoflorentina", "cinnamonandcoriander", "cleanfoodcrush", "closetcooking",
    "coleycooks", "completelydelicious", "connoisseurusveg", "cookathomemom", "cookcookgo",
    "cookieandkate", "cookiemadness", "cookiesandcups", "cookincanuck", "cookingchew",
    "cookingclassy", "cookingforkeeps", "cookingformysoul", "cookingfromheart", "cookinglsl",
    "cookingwithruthie", "cookjunkie", "cookrepublic", "cookshideout", "cooktoria", "cookwithkushi",
    "cookwithmanali", "cookwithnabeela", "copykat", "coupleinthekitchen", "craftbeering",
    "crazyforcrust", "createbakemake", "crunchycreamysweet", "cubesnjuliennes", "cuisineandtravel",
    "culinaryginger", "culinaryhill", "cupcakesandkalechips", "curiouscuisiniere",
    "curlygirlkitchen", "currytrail", "dadwithapan", "dailydishrecipes", "damnspicy",
    "dancearoundthekitchen", "daringgourmet", "davidlebovitz", "deliciousfromscratch",
    "deliciouslysprinkled", "deliciousmeetshealthy", "delicioustable", "delightfuladventures",
    "delmonte", "dessertfortwo", "dessertswithbenefits", "detoxinista", "diethood", "dineanddish",
    "dinneratthezoo", "dinnersdishesanddesserts", "dishesdelish", "dizzybusyandhungry",
    "dobbyssignature", "domesticateme", "domesticgothess", "domesticsuperhero",
    "dontgobaconmyheart", "dontsweattherecipe", "downredbuddrive", "downshiftology",
    "drizzleanddip", "easyanddelish", "easycheesyvegetarian", "easypeasyfoodie", "easyrecipedepot",
    "easysavory", "eatingbirdfood", "eatingeuropean", "eatingrules", "eatthegains",
    "eatwithclarity", "eatwithohashi", "eatyourselfskinny", "edmonds_nz", "effortlessfoodie",
    "egglesscooking", "elanaspantry", "elavegan", "elephantasticvegan", "elizabethskitchendiary",
    "emilybites", "emilyenchanted", "entertainingwithbeth", "errenskitchen", "evergreenkitchen",
    "everydaymaven", "everylastbite", "evolvingtable", "fabfood4all", "fabulesslyfrugal",
    "familyfreshmeals", "familystylefood", "fannetasticfood", "farmgirlgourmet", "fatgirlskinny",
    "fearlessdining", "feastandfarm", "fedandfit", "feelgoodfoodie", "feistytapas",
    "firstdayofhome", "fitfoodiefinds", "fivehearthome", "flavcity", "flavourandsavour",
    "flawlessfood", "flouronmyface", "floursandfrostings", "foodbanjo", "foodfaithfitness",
    "foodieandwine", "foodiewithfamily", "foodmeanderings", "foodnetwork_uk", "foodnourish",
    "foodwithfeeling", "foolproofliving", "forkandtwist", "fortheloveofcooking", "foxandbriar",
    "freshsavory", "fromachefskitchen", "frommybowl", "fromscratchfast", "fromvalerieskitchen",
    "fullofplants", "funfoodfrolic", "garnishandglaze", "gatheranddine", "gatheringdreams",
    "georgeats", "getinspiredeveryday", "giangiskitchen", "gimmedelicious", "gimmesomegrilling",
    "gimmesomeoven", "girlcarnivore", "girlversusdough", "glueandglitter",
    "glutenfreeonashoestring", "glutenkitchen", "godairyfree", "gooddinnermom", "goodlifeeats",
    "graceandgoodeats", "grandbabycakes", "gratefulgrazer", "greatbritishchefs",
    "greatgrubdelicioustreats", "greedygourmet", "greenbowl2soul", "greensnchocolate",
    "gritsandgouda", "growagoodlife", "grownupdish", "halfbakedharvest", "handletheheat",
    "happyfoodstube", "happyketo", "happykidskitchen", "happymoneysaver", "healthfulblondie",
    "healthmylifestyle", "healthydelicious", "healthyfitnessmeals", "healthykitchen",
    "healthylittlefoodies", "healthynibblesandbits", "healthyseasonalrecipes", "heartbeetkitchen",
    "heatherlikesfood", "hebbarskitchen", "herbsandflour", "highlandsranchfoodie", "hipfoodiemom",
    "holycowvegan", "homecookingadventure", "homeinthekitchen", "homemadeinterest", "honeyandbirch",
    "hotchocolatehits", "houseofnasheats", "houseofyumm", "howsweeteats", "hummingbirdhigh",
    "hurrythefoodup", "iambaker", "ifoodreal", "ifyougiveablondeakitchen", "ihearteating",
    "iheartnaptime", "indianveggiedelight", "inmamamaggieskitchen", "inspiredtaste",
    "inthekitchenwithmatt", "iowagirleats", "irishamericanmom", "isabeleats",
    "itdoesnttastelikechicken", "itsalwaysautumn", "itsavegworldafterall",
    "itsnotcomplicatedrecipes", "itstartswithgoodfood", "jamieoliver", "janespatisserie",
    "jaroflemons", "jeanetteshealthyliving", "jessicagavin", "jessicalevinson", "joyfilledeats",
    "joyfoodsunshine", "joyfulhealthyeats", "joythebaker", "juliasalbum", "julieblanner",
    "justaddglam", "justataste", "justinesnacks", "justonecookbook", "kalynskitchen",
    "katiebirdbakes", "kellyneil", "ketoconnect", "ketocookingchristian", "keviniscooking",
    "kimscravings", "kitchenconfidante", "kitchenfrau", "kitchenofdebjani", "kitchensanctuary",
    "kitchentreaty", "knifeandsoul", "kristineskitchenblog", "krollskorner", "krumpli",
    "landolakes", "laraclevenger", "larderlove", "laughingspatula", "laurenslatest",
    "lavenderandlovage", "layersofhappiness", "lazycatkitchen", "lecremedelacrumb", "lemonsandzest",
    "lemontreedwelling", "lexiscleankitchen", "lifeloveandsugar", "lifemadesweeter",
    "lillieeatsandtells", "lilluna", "littlehouseliving", "littlespicejar", "littlesunnykitchen",
    "littlesweetbaker", "liveeatlearn", "livewellbakeoften", "livforcake", "livinglou", "lmld",
    "loveandlemons", "loveandoliveoil", "lovebakesgoodcakes", "lovefoodnotcooking", "lovingitvegan",
    "lowcarbdelish", "lowcarbspark", "macheesmo", "madaboutfood", "maebells", "makeandtakes",
    "mamabearscookbook", "mandysrecipeboxblog", "manjulaskitchen", "maplewoodroad",
    "mariasmixingbowl", "masalaherb", "masonfit", "mealplanningmagic", "mealpreponfleek",
    "meaningfuleats", "meganvskitchen", "melissassouthernstylekitchen", "melskitchencafe",
    "merryboosters", "midgetmomma", "mightymrs", "milkandpop", "minimalistbaker", "ministryofcurry",
    "mississippivegan", "modernbites", "moderncrumb", "modernhoney", "modernyum",
    "mommyhatescooking", "momontimeout", "munatycooking", "muydelish", "mybakingaddiction",
    "mydarlingvegan", "myfoodstory", "myheartbeets", "mykoreankitchen", "mylatinatable",
    "mynewroots", "mypocketkitchen", "mypureplants", "myquietkitchen", "mysequinedlife",
    "mytastycurry", "myveganminimalist", "n100daysofrealfood", "n365daysofbakingandmore",
    "natashaskitchen", "naturallyella", "neighborfoodblog", "neilshealthymeals", "noracooks",
    "nordicfoodliving", "nourishplate", "nutritiouseats", "nyssaskitchen", "ohmyfoodrecipes",
    "ohmyveggies", "olgasflavorfactory", "olivemagazine", "olivetomato", "oliviascuisine",
    "omgyummy", "onceuponachef", "onehotoven", "onelovelylife", "onepotrecipes", "onesweetappetite",
    "onmykidsplate", "orchidsandsweettea", "organicfacts", "orsoshesays", "orwhateveryoudo",
    "ourbestbites", "ourtableforseven", "paleoglutenfree", "paleoleap", "paleorunningmomma",
    "pancakerecipes", "panlasangpinoy", "passthesushi", "pastrieslikeapro", "peaceloveandlowcarb",
    "peanutblossom", "peasandcrayons", "peelwithzeal", "pepperbowl", "perrysplate", "pickledplum",
    "pillsbury", "pinchandswirl", "pinchofyum", "pinkowlkitchen", "pinoyrecipe", "pipandebby",
    "pipingpotcurry", "plainchicken", "plantbasedonabudget", "plantyou", "platedcravings",
    "platingsandpairings", "powerhungry", "practicalselfreliance", "preppykitchen",
    "pressurecookingtoday", "prettydeliciouslife", "primaverakitchen", "princesspinkygirl",
    "profusioncurry", "progresso", "projectmealplan", "pumpkinnspice", "pureandsimplenourishment",
    "rachelcooksthai", "rachlmansfield", "rachnaskitchen", "rainbowplantlife", "rakskitchen",
    "ramonascuisine", "rasamalaysia", "recipedish", "recipegirl", "reciperunner",
    "recipesfromitaly", "recipesthatcrock", "recipethis", "recipetineats", "redhousespice",
    "reluctantentertainer", "reluctantgourmet", "rhiansrecipes", "ricardocuisine", "rockrecipes",
    "roseclearfield", "runningonrealfood", "runningtothekitchen", "salads4lunch", "saltandlavender",
    "saltpepperskillet", "saltysidedish", "savorandsavvy", "savortheflavour", "savoryexperiments",
    "savorynothings", "savvybites", "savvysavingcouple", "scandikitchen", "scrummylane",
    "searchingforspice", "seasonalcravings", "shelikesfood", "shelovesbiscotti", "showmetheyummy",
    "shugarysweets", "simplejoy", "simpleveganblog", "simplylakita", "simplyquinoa",
    "simplyscratch", "simplysogood", "simplystacie", "simplyvegetarian777", "sipandspice",
    "sixsistersstuff", "skinnykitchen", "skinnyms", "skinnytaste", "slapdashmom",
    "slowcookerkitchen", "slowthecookdown", "smalltownwoman", "smartlittlecookie", "smittenkitchen",
    "snappygourmet", "somewhatsimple", "southernbite", "spainonafork", "spam", "spendwithpennies",
    "spiceeats", "spiceupthecurry", "spicysouthernkitchen", "spoonforkbacon", "spoonnest",
    "spoonrecipes", "staysnatched", "steamykitchen", "stephgaudreau", "stockpilingmoms",
    "sugarandsoul", "sugarfreelondoner", "sugarfreemom", "sugarsaltmagic", "sugarspunrun",
    "sundaysuppermovement", "sunkissedkitchen", "sunset", "supergoldenbakes", "sustainablecooks",
    "sweetandsavorymeals", "sweetcsdesigns", "sweetlysplendid", "sweetmouthjoy",
    "sweetpeasandsaffron", "sweetpeaskitchen", "sweetphi", "sweetpotatosoul", "sweetsimplevegan",
    "sweetteaandthyme", "tablefortwoblog", "tamingtwins", "tasteandsee", "tasteandtellblog",
    "tasteofhome", "tastesbetterfromscratch", "tasteslovely", "tastesofhomemade", "tesco_recipes",
    "thatgirlcookshealthy", "thatlowcarblife", "thatskinnychickcanbake", "thebeachhousekitchen",
    "thebigmansworld", "theblackpeppercorn", "theblondcook", "thebusybaker", "thebutterhalf",
    "thecafesucrefarine", "thecakeblog", "thecastawaykitchen", "thecheekychickpea", "thechunkychef",
    "thecleaneatingcouple", "thecookful", "thecookierookie", "thecookingfoodie", "thecookreport",
    "thecountrycook", "thecozyplum", "thecreativebite", "thecuriousplate", "thedefineddish",
    "thedizzycook", "thedomesticrebel", "theendlessmeal", "thefeatherednester", "thefedupfoodie",
    "theflavorbender", "theflavoursofkitchen", "theflexitarian", "theflexitarian_ir", "thefoodblog",
    "thefoodcharlatan", "thefoodietakesflight", "theforkedspoon", "thegardengrazer",
    "thegestationaldiabetic", "thegingeredwhisk", "thegirlonbloor", "thegirlwhoateeverything",
    "thegoodheartedwoman", "thegraciouspantry", "thegunnysack", "thehappierhomemaker",
    "thehealthyfoodie", "thehealthymaven", "theheirloompantry", "theholymess", "theinspiredhome",
    "thekitchenmagpie", "thekittchen", "thekoreanvegan", "thelittleepicurean", "theliveinkitchen",
    "themagicalslowcooker", "themamasgirls", "themediterraneandish", "themerrythought",
    "themodernnonna", "thenaturalnurturer", "thenovicechefblog", "theorganickitchen",
    "thepalatablelife", "thepancakeprincess", "thepetitecook", "thepinningmama",
    "theplantbasedschool", "theppk", "theprettybee", "theproteinchef", "therealfoodgeek",
    "therealfoodrds", "therecipecritic", "thereciperebel", "therecipewell", "theroastedroot",
    "therusticfoodie", "thesaltymarshmallow", "thesavory", "theseasonedmom", "thesimpleparent",
    "theskinnyishdish", "thesophisticatedcaveman", "thesouthernladycooks", "thestayathomechef",
    "thestonesoup", "thesuburbansoapbox", "thesugarkitchen", "thetoastykitchen",
    "thevanillabeanblog", "thevegspace", "thevietvegan", "theviewfromgreatisland",
    "thevintagemixer", "thewanderlustkitchen", "thewholecook", "thewholesomedish", "thewoksoflife",
    "thiswifecooks", "throughherlookingglass", "throughthefibrofog", "tidymom",
    "tiffinandteaofficial", "tiffycooks", "tillamook", "todaysdelight", "togetherasfamily",
    "toriavey", "tornadoughalli", "traditionallymodernfood", "triedandtruerecipe", "twocupsflour",
    "twohealthykitchens", "twopeasandtheirpod", "twosleevers", "urbancowgirllife",
    "valentinascorner", "vanillaandbean", "veganricha", "veggieinspired", "veggiesdontbite",
    "vegkitchen", "vietworldkitchen", "walkingonsunshinerecipes", "wandercooks", "watchwhatueat",
    "wellplated", "whatgreatgrandmaate", "whatjessicabakednext", "whatmollymade",
    "whatsgabycooking", "whereismyspoon", "whiskaffair", "whiskbite", "whiskrecipes",
    "whiteonricecouple", "wholeandheavenlyoven", "wholegirl", "wholelottayum", "wholesomelicious",
    "wholesomepatisserie", "wholesomerecipebox", "wholesomeyum", "willcookforsmiles",
    "wishesndishes", "withfoodandlove", "withspice", "wokandkin", "wokandskillet", "woonheng",
    "worldofvegan", "yellowblissroad", "yellowthyme", "yourhomebasedmom", "yummyeats",
    "yummyhealthyeasy", "yummytoddlerfood", "yupitsvegan", "zestfulkitchen",
  ],
};

const LANGUAGE_BY_SOURCE = new Map<string, RecipeSourceLanguage>(
  Object.entries(RECIPE_SOURCE_IDS_BY_LANGUAGE).flatMap(([language, ids]) =>
    ids.map((id): [string, RecipeSourceLanguage] => [id, language as RecipeSourceLanguage])
  )
);

/** Resolve canonical source IDs only; unknown sources have no inferred language. */
export function recipeSourceLanguage(sourceId: string): RecipeSourceLanguage | undefined {
  return LANGUAGE_BY_SOURCE.get(sourceId);
}

export function parseRecipeSourceLanguages(value: string): RecipeSourceLanguage[] {
  const aliases: Record<string, RecipeSourceLanguage> = {
    da: "da", danish: "da", dansk: "da", en: "en", english: "en",
  };
  const values = value.split(",").map((language) => language.trim().toLowerCase());
  if (values.some((language) => !Object.hasOwn(aliases, language))) {
    throw new Error('--language must be da (Danish), en (English), or da,en');
  }
  return [...new Set(values.map((language) => aliases[language]))];
}
