/**
 * Static migration inventory for legacy WprmApiSpider subclasses whose
 * effective locale is `danish_recipes`. Keeping this independent of the
 * Scrapy checkout makes the Crawlee runtime deployable on its own.
 *
 * Tuple fields: source id, legacy class, source domain, API endpoint,
 * Playwright transport, delay seconds, max concurrency.
 */
export const DANISH_WPRM_SOURCE_DEFINITIONS = [
  ["airfryerkogebogen", "AirfryerKogebogenSpider", "airfryerkogebogen.dk", "https://airfryerkogebogen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["airfryermad", "AirfryerMadSpider", "airfryermad.dk", "https://airfryermad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["albertestengaard", "AlbertestengaardSpider", "albertestengaard.dk", "https://albertestengaard.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["alcayaga", "AlcayagaSpider", "alcayaga.dk", "https://alcayaga.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["altmad", "AltmadSpider", "altmad.dk", "https://www.altmad.dk/wp-json/wp/v2/wprm_recipe", false, 10, 1],
  ["amorsmadklub", "AmorsMadklubSpider", "amorsmadklub.dk", "https://amorsmadklub.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["annamaddk", "AnnaMadDkSpider", "anna-mad.dk", "https://anna-mad.dk/wp-json/wp/v2/wprm_recipe", true, 1, 2],
  ["annesondergaard", "AnneSondergaardSpider", "annesondergaard.dk", "https://annesondergaard.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["avocadoen", "AvocadoenSpider", "avocadoen.dk", "https://avocadoen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["bageglad", "BagegladSpider", "bageglad.dk", "https://bageglad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["bagvrk", "BagvrkSpider", "bagvrk.dk", "https://bagvrk.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["baregomad", "BaregomadSpider", "baregomad.dk", "https://baregomad.dk/wp-json/wp/v2/wprm_recipe", true, 1, 2],
  ["bedstemorskogebog", "BedstemorsKogebogSpider", "bedstemorskogebog.dk", "https://www.bedstemorskogebog.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["benedictesmad", "BenedictesMadSpider", "benedictesmad.dk", "https://benedictesmad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["bergholts", "BergholtsSpider", "bergholts.dk", "https://bergholts.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["bondemad", "BondemadSpider", "bondemad.dk", "https://bondemad.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["camillemaja", "CamilleMajaSpider", "camillemaja.dk", "https://camillemaja.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["chilisauce", "ChilisauceSpider", "chilisauce.dk", "https://chilisauce.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["chokomils", "ChokomilsSpider", "chokomils.com", "https://chokomils.com/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["cookingclub", "CookingClubSpider", "cookingclub.dk", "https://cookingclub.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["dagenstallerken", "DagensTallerkenSpider", "dagenstallerken.dk", "https://dagenstallerken.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["danishthings", "DanishThingsSpider", "danishthings.com", "https://danishthings.com/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["dansktang", "DanskTangSpider", "dansktang.dk", "https://www.dansktang.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["drkoch", "DrKochSpider", "drkoch.dk", "https://drkoch.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["emmaolsen", "EmmaolsenSpider", "emmaolsen.dk", "https://emmaolsen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["frahaventilmaven", "FraHavenTilMavenSpider", "frahaventilmaven.dk", "https://frahaventilmaven.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["frukreativ", "FruKreativSpider", "frukreativ.dk", "https://frukreativ.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["fuldkorn", "FuldkornSpider", "fuldkorn.dk", "https://www.fuldkorn.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["gastrofun", "GastrofunSpider", "gastrofun.dk", "https://gastrofun.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["gastromad", "GastromadSpider", "gastromad.dk", "https://gastromad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["gastromand", "GastromandSpider", "gastromand.dk", "https://gastromand.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["gastry", "GastrySpider", "gastry.dk", "https://gastry.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["gourministeriet", "GourministerietSpider", "gourministeriet.dk", "https://gourministeriet.dk/wp-json/wp/v2/wprm_recipe", true, 1, 2],
  ["grilltips", "GrilltipsSpider", "grilltips.dk", "https://grilltips.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["groedgrisen", "GroedgrisenSpider", "groedgrisen.dk", "https://groedgrisen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["hashtagmor", "HashtagmorSpider", "hashtagmor.dk", "https://hashtagmor.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["homebybianca", "HomeByBiancaSpider", "homebybianca.dk", "https://www.homebybianca.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["hurtigmums", "HurtigMumsSpider", "hurtigmums.dk", "https://www.hurtigmums.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["hverdagsro", "HverdagsroSpider", "hverdagsro.dk", "https://www.hverdagsro.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["italienskvinogmad", "ItalienskVinOgMadSpider", "italienskvinogmad.dk", "https://italienskvinogmad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["jensensmadblog", "JensensMadblogSpider", "jensens-madblog.dk", "https://jensens-madblog.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["johanjohansen", "JohanjohansenSpider", "johanjohansen.dk", "https://johanjohansen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["juliebruun", "JuliebruunSpider", "juliebruun.com", "https://juliebruun.com/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["juliekarla", "JuliekarlaSpider", "juliekarla.dk", "https://www.juliekarla.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["kagefest", "KagefestSpider", "kagefest.dk", "https://kagefest.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["karinabaagoe", "KarinaBaagoeSpider", "karinabaagoe.dk", "https://www.karinabaagoe.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["ketoliv", "KetolivSpider", "ketoliv.dk", "https://ketoliv.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["koudahl", "KoudahlSpider", "koudahl.dk", "https://koudahl.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["letmad", "LetmadSpider", "letmad.dk", "https://letmad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["louiogbearnaisen", "LouiOgBearnaisenSpider", "louiogbearnaisen.dk", "https://louiogbearnaisen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["louisesmadblog", "LouisesmadblogSpider", "louisesmadblog.dk", "https://louisesmadblog.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["madbanditten", "MadbandittenSpider", "madbanditten.dk", "https://www.madbanditten.dk/wp-json/wp/v2/wprm_recipe", false, 100, 1],
  ["madensverden", "MadensverdenSpider", "madensverden.dk", "https://madensverden.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["madentusiasten", "MadentusiastenSpider", "madentusiasten.dk", "https://madentusiasten.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["madfilosofie", "MadfilosofieSpider", "madfilosofie.dk", "https://madfilosofie.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["madmors", "MadmorsSpider", "madmors.dk", "https://madmors.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["madmusen", "MadmusenSpider", "madmusen.dk", "https://madmusen.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["madogkaerlighed", "MadogkaerlighedSpider", "madogkaerlighed.dk", "https://madogkaerlighed.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["madogmonopolet", "MadOgMonopoletSpider", "madogmonopolet.dk", "https://madogmonopolet.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["madskribent", "MadskribentSpider", "madskribent.dk", "https://madskribent.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["majspassion", "MajspassionSpider", "majspassion.dk", "https://majspassion.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["marialottes", "MarialottesSpider", "marialottes.dk", "https://marialottes.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["mariasilje", "MariasiljeSpider", "mariasilje.dk", "https://mariasilje.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["mettesmadmagi", "MettesMadmagiSpider", "mettesmadmagi.dk", "https://mettesmadmagi.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["minmadopskrift", "MinMadopskriftSpider", "minmadopskrift.dk", "https://minmadopskrift.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["minopskrift", "MinOpskriftSpider", "min-opskrift.dk", "https://www.min-opskrift.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["muttionline", "MuttionlineSpider", "muttionline.dk", "https://muttionline.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["nemlchf", "NemLchfSpider", "nem-lchf.dk", "https://www.nem-lchf.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["nerdytreats", "NerdyTreatsSpider", "nerdytreats.dk", "https://nerdytreats.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["newyorkerbyheart", "NewyorkerByHeartSpider", "newyorkerbyheart.dk", "https://newyorkerbyheart.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["onekitchenblog", "OneKitchenBlogSpider", "onekitchenblog.com", "https://onekitchenblog.com/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["opskrifteriet", "OpskrifterietSpider", "opskrifteriet.dk", "https://opskrifteriet.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["opskriftnet", "OpskriftNetSpider", "opskrift.net", "https://opskrift.net/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["opskriftorg", "OpskriftOrgSpider", "opskrift.org", "https://opskrift.org/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["pigenikoekkenet", "PigenIKoekkenetSpider", "pigenikoekkenet.dk", "https://pigenikoekkenet.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["pilenskoekken", "PilensKoekkenSpider", "pilenskoekken.dk", "https://pilenskoekken.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["planteaederen", "PlanteaederenSpider", "planteaederen.dk", "https://planteaederen.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["rasmussmedstrup", "RasmusSmedstrupSpider", "rasmussmedstrup.dk", "https://rasmussmedstrup.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["rigeligtsmor", "RigeligtSmorSpider", "rigeligtsmor.dk", "https://rigeligtsmor.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["sabinasverden", "SabinasVerdenSpider", "sabinasverden.com", "https://sabinasverden.com/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["sixpm", "SixPmSpider", "6pm.dk", "https://www.6pm.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["sundfamiliemad", "SundFamiliemadSpider", "sundfamiliemad.dk", "https://sundfamiliemad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["sundmor", "SundMorSpider", "sund-mor.dk", "https://sund-mor.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["surdejmedsophie", "SurdejMedSophieSpider", "surdejmedsophie.dk", "https://www.surdejmedsophie.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["twinfood", "TwinFoodSpider", "twin-food.dk", "https://twin-food.dk/wp-json/wp/v2/wprm_recipe", true, 20, 1],
  ["veganernu", "VeganerNuSpider", "veganer.nu", "https://veganer.nu/wp-json/wp/v2/wprm_recipe", false, 1, 2],
  ["vforvegetarisk", "VForVegetariskSpider", "vforvegetarisk.dk", "https://vforvegetarisk.dk/wp-json/wp/v2/wprm_recipe", true, 2, 1],
  ["vielskermad", "VielskermadSpider", "vielskermad.dk", "https://vielskermad.dk/wp-json/wp/v2/wprm_recipe", false, 1, 2],
] as const;

export type DanishWprmSourceDefinition =
  (typeof DANISH_WPRM_SOURCE_DEFINITIONS)[number];
